# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH

# Path to your Oh My Zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time Oh My Zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="arrow"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
# plugins=(git)
plugins=(git zsh-autosuggestions)


source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='nvim'
# fi
export EDITOR=nvim
export VISUAL=nvim


# Compilation flags
# export ARCHFLAGS="-arch $(uname -m)"

# Set personal aliases, overriding those provided by Oh My Zsh libs,
# plugins, and themes. Aliases can be placed here, though Oh My Zsh
# users are encouraged to define aliases within a top-level file in
# the $ZSH_CUSTOM folder, with .zsh extension. Examples:
# - $ZSH_CUSTOM/aliases.zsh
# - $ZSH_CUSTOM/macos.zsh
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
#


# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#     _         _        _                 _ _ 
#    / \  _   _| |_ ___ | | ___   __ _  __| (_)_ __   __ _ 
#   / _ \| | | | __/ _ \| |/ _ \ / _` |/ _` | | '_ \ / _` |
#  / ___ \ |_| | || (_) | | (_) | (_| | (_| | | | | | (_| |
# /_/   \_\__,_|\__\___/|_|\___/ \__,_|\__,_|_|_| |_|\__, |
#                                                    |___/
#
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

autoload -Uz compinit
compinit


# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
#    _  __          _     _           _ _                    #
#   | |/ /___ _   _| |__ (_)_ __   __| (_)_ __   __ _ ___    #
#   | ' // _ \ | | | '_ \| | '_ \ / _` | | '_ \ / _` / __|   #
#   | . \  __/ |_| | |_) | | | | | (_| | | | | | (_| \__ \   #
#   |_|\_\___|\__, |_.__/|_|_| |_|\__,_|_|_| |_|\__, |___/   #
#             |___/                             |___/        #
#                                                            #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
         
bindkey '^[[Z' autosuggest-accept


# # # # # # # # # # # # # # # # # 
#     ___  _   _                  #
#    / _ \| |_| |__   ___ _ __    #
#   | | | | __| '_ \ / _ \ '__|   #
#   | |_| | |_| | | |  __/ |      #
#    \___/ \__|_| |_|\___|_|      #
#                                 #
#                                 #
# # # # # # # # # # # # # # # # # 


# Info
alias infoRpi="/home/ssbrpi/ProjectRpi/Rpi/rpiPerformance.sh"
alias infoServices="systemctl list-units --type=service --state=running"

# Logs
alias logTempMeasurement='tail -f /home/ssbrpi/ProjectRpi/Rpi/Background/Logs/tempMeasurement_$(date +%F).log'

# Python
alias pythonCustomKeyboard='sudo python /home/ssbrpi/ProjectRpi/Rpi/CustomKeyboard/main.py'

# Directories
alias cdCustomKeyboard='cd /home/ssbrpi/ProjectRpi/Rpi/CustomKeyboard/'
alias cdPersonalAssistant='cd ~/ProjectRpi/Rpi/PersonalAssistant/'
# system.md files /etc/systemd/system

alias v='nvim'

alias dockerPersonalAssistant="sudo docker rm ollamaLocal -f && \
sudo docker run -d --rm -v ollama:/root/.ollama -v /home/ssbrpi/ProjectRpi:/root/ProjectRpi/ -p 11434:11434 --name ollamaLocal personal_assistant && \
sudo docker exec -it ollamaLocal sh -c '. /root/.profile; exec sh -l'"

# Git
alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gp='git push'
alias gauth='. ./GitAuthentication/gitAuthentication.sh'

# Navigation
alias ..='cd ..'
alias ...='cd ../../../'

# Quick small tasks
alias c='clear'


# OpenClaw Completion
# source "/home/ssbrpi/.openclaw/completions/openclaw.zsh"
# export PATH="$HOME/.npm-global/bin:$PATH"


# Welcome message

clear

echo "========================================="
# echo "        ███████╗███████╗██████╗"
# echo "        ██╔════╝██╔════╝██╔══██╗"
# echo "        ███████╗███████╗██████╔╝"
# echo "        ╚════██║╚════██║██╔══██╗"
# echo "        ███████║███████║██████╔╝"
# echo "        ╚══════╝╚══════╝╚═════╝"
echo ""
echo "🟢 Welcome back, "
echo " _____   _____   _____"
echo "/  ___| /  ___| | __  |"
echo "\\ \`--.  \\ \`--.  | |_/ /"
echo " \`--. \\  \`--. \\ | ___ \\"
echo "/\\__/ / /\\__/ / | |_/ /"
echo "\\____/  \\____/  \\____/"
echo ""
echo ""
echo "⚡ Environment initialized successfully."
echo "📅 $(date '+%A, %d %B %Y')"
echo "🕒 $(date '+%H:%M:%S')"
echo "💻 Happy coding!"
echo "========================================="
echo ""
# echo ""
# echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
# echo "👋 Welcome SSB!"
# echo "✅ Your configuration has been loaded."
# echo "📅 $(date '+%A, %d %B %Y')"
# echo "🕒 $(date '+%I:%M:%S %p')"
# echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
# echo ""
